name: Build and Push BindCraft to Docker Hub

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Create Dockerfile
      run: |
        cat > Dockerfile << 'EOF'
        FROM nvidia/cuda:12.9.1-cudnn-runtime-ubuntu22.04
        
        RUN export DEBIAN_FRONTEND=noninteractive && \
            apt-get update && apt-get install -y \
                python3 python3-pip git wget \
                libgfortran5 libgomp1 && \
            rm -rf /var/lib/apt/lists/*
        
        RUN pip install --no-cache-dir \
                jax==0.4.35 jaxlib==0.4.35 \
                numpy==2.0.1 scipy==1.15.3 \
                pandas matplotlib biopython \
                git+https://github.com/sokrypton/ColabDesign.git \
                pyrosetta-installer pdbfixer
        
        RUN git clone https://github.com/martinpacesa/BindCraft /BindCraft && \
            chmod +x /BindCraft/functions/dssp /BindCraft/functions/DAlphaBall.gcc && \
            mkdir -p /BindCraft/params
        
        ENV PYTHONPATH=/BindCraft:$PYTHONPATH
        
        WORKDIR /workspace
        ENTRYPOINT ["python3", "/BindCraft/bindcraft.py"]
        EOF
    
    - name: Build and test locally
      run: |
        docker build -t bindcraft-local .
        docker run --rm bindcraft-local python3 -c "print('✓ Container works')"
        
        # Create Singularity-compatible version
        docker save bindcraft-local | gzip > bindcraft.tar.gz
        
        echo "✓ Docker image ready for conversion to Singularity"
        echo "Image size: $(du -h bindcraft.tar.gz | cut -f1)"
    
    - name: Upload Docker image
      uses: actions/upload-artifact@v4
      with:
        name: bindcraft-docker-image
        path: bindcraft.tar.gz
        retention-days: 30
    
    - name: Instructions
      run: |
        echo "============================================"
        echo "✅ BindCraft Docker image ready!"
        echo "============================================"
        echo ""
        echo "TO CONVERT TO SINGULARITY:"
        echo "1. Download bindcraft.tar.gz from artifacts"
        echo "2. Run: gunzip bindcraft.tar.gz"
        echo "3. Run: singularity build bindcraft.sif docker-archive://bindcraft.tar"
        echo ""
        echo "OR USE DOCKER DIRECTLY:"
        echo "docker load < bindcraft.tar"
        echo "docker run --gpus all -v /path/to/data:/workspace bindcraft-local --settings config.json"
